ci:
  autofix_prs: false
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v5.0.0
    hooks:
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: name-tests-test
      - id: double-quote-string-fixer
  - repo: 'https://github.com/codespell-project/codespell'
    rev: v2.2.6
    hooks:
      - id: codespell
        exclude: ^(data/|figures/)
  - repo: 'https://github.com/charliermarsh/ruff-pre-commit'
    rev: v0.1.7
    hooks:
      - id: ruff
        args:
          - '--fix'
          - '--exit-non-zero-on-fix'
      - id: ruff-format
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.14.0
    hooks:
    -   id: reorder-python-imports
        args: [--py310-plus, --add-import, 'from __future__ import annotations']
