name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    name: Rux tox
    runs-on: ubuntu-latest
    environment: hpcci

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.4'
          cache: 'pip'
      - name: execute tests
        id: pytest
        uses: ValHayot/globus-compute-github-action@v1
        with:
          client_id: ${{ secrets.GLOBUS_COMPUTE_CLIENT_ID }}
          client_secret: ${{ secrets.GLOBUS_COMPUTE_CLIENT_SECRET }}
          endpoint_uuid: '9edd8398-6091-4138-abd8-e6ea11c5601c'
          shell_cmd: 'cd gc-action-temp/parsl-docking-tutorial && tox'
      - name: Archive output stdout
        uses: actions/upload-artifact@v4
        with:
          name: pytest-stdout
          path: ${{ steps.pytest.outputs.stdout }}
      - name: Archive output stderr
        uses: actions/upload-artifact@v4
        with:
          name: pytest-stderr
          path: ${{ steps.pytest.outputs.stderr }}
      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.response }}"
